# Generated by Django 3.2.8 on 2021-10-30 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisior_info',
            name='advisior_profile_pic',
            field=models.URLField(),
        ),
    ]
